image:
  main:
    repository: ghcr.io/mt190502/docker-anki-sync-server
    pullPolicy: IfNotPresent
    # tag: 25.02.4

global:
  main:
    ports:
      - containerPort: 8080
    accounts:
      - key: SYNC_USER1
        name: admin
        password: my_strong_password
        secret:
          enabled: true
          autoCreate: true
          name: user1-secret
          key: credentials
    environments: {}

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

resources:
  limits:
    main:
      memory: 512Mi
  requests:
    main:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}